version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: agentsdb
